image: Visual Studio 2017

platform:
  - x64

environment:
  nodejs_version: "12"

# Install scripts
install:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

  # Get the latest LTS version of Node.js 12
  - ps: Install-Product node $env:nodejs_version x64

  # Add Wix to Build Path
  - dir "c:\Program Files (x86)\WiX Toolset"*
  - set PATH="c:\Program Files (x86)\WiX Toolset v3.11\bin";%PATH%

  # Set NPM to use Visual Studio 2017
  - npm config set msvs_version "2017"
  
  # Set NPM to use Python x64
  - npm config set python "C:\\Python27-x64\\pythonw.exe"
  
  # Install Packages
  - npm install

  # Rebuild native packages
  # Install SQLite from Source (Native Module)
  - npm install sqlite3@3.1.4 --build-from-source --runtime=electron --target=8.3.0 --dist-url=https://electronjs.org/headers
  
build_script:
  - set PATH=C:\projects\sete\node_modules\.bin;%PATH%
  - electron-forge make

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))




