image: Visual Studio 2017

platform:
  - x64

environment:
  nodejs_version: "12"

# Install scripts
install:
  # Get the latest LTS version of Node.js 12
  - ps: Install-Product node $env:nodejs_version x64
  # Install Windows Build Tools
  - dir "c:\Program Files (x86)\WiX Toolset"*
  - set PATH="c:\Program Files (x86)\WiX Toolset v3.11\bin";%PATH%
  - echo %PATH%

